version: "3.9"

services:
  mysql:
    image: mysql:8.4

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}

    ports:
      - "${DB_PORT}:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .

    restart: unless-stopped

    depends_on:
      - mysql

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}

    ports:
      - "${PORT}:${PORT}"

volumes:
  mysql_data: