-- +goose Up
CREATE TABLE IF NOT EXISTS `table_location` (
    `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,

    `name` VARCHAR(64) NOT NULL,
    `slug` VARCHAR(64) UNIQUE NOT NULL,
    `room_code` VARCHAR(32) NULL,
    `description` TEXT NULL,

    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE IF EXISTS `table_location`;