-- +goose Up
CREATE TABLE IF NOT EXISTS `table_brand` (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,

    `name` TEXT NOT NULL,
    `slug` TEXT UNIQUE NOT NULL,

    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- +goose Down
DROP TABLE IF EXISTS `table_brand`;