name: Unit and Service Testing CI

on:
  push:
    branches:
      - sqlite-main
      - "feature/**"
    paths:
      - "internal/**"
      - "cmd/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/unit-service-testing-ci.yml"

  pull_request:
    branches:
      - sqlite-main
      - "feature/**"
    paths:
      - "internal/**"
      - "cmd/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/unit-service-testing-ci.yml"

jobs:
  service-test:
    name: Run Unit and Service Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install Dependencies
        run: go mod download

      - name: Run Unit and Service Tests
        run: go test -v ./...
